export const matchs = [
  {
    date: "2025-08-08",
    heure: "8:30",
    equipeA: "GNVB",
    equipeB: "ASSM",
    lieu: "Arena sport Toamasina",
    competition: "U-16",
    categorie: "Homme",
    logoA: "/assets/image/etats-unis.png",
    logoB: "/assets/image/france.png",
    termine: false,
    resultat: "",
    score: ""
  },
  {
    date: "2025-08-09",
    heure: "11:30",
    equipeA: "CSA",
    equipeB: "CVBA",
    lieu: "Arena sport Toamasina",
    competition: "U-18",
    categorie: "Homme",
    logoA: "/assets/image/france.png",
    logoB: "/assets/image/italie.png",
    termine: true,
    resultat: "3 - 0",
    score: "25-10 | 25-20 | 25-16"
  },
  {
    date: "2025-08-08",
    heure: "7:00",
    equipeA: "ASI",
    equipeB: "2AVB",
    lieu: "Arena sport Toamasina",
    competition: "U-16",
    categorie: "Femme",
    logoA: "/assets/image/allemagne.png",
    logoB: "/assets/image/etats-unis.png",
    termine: true,
    resultat: "1 - 3",
    score: "20-25 | 18-25 | 25-22 | 15-25"
  },
  {
    date: "2025-08-10",
    heure: "11:30",
    equipeA: "ASI",
    equipeB: "CVBA",
    lieu: "Arena sport Toamasina",
    competition: "U-18",
    categorie: "Homme",
    logoA: "/assets/image/allemagne.png",
    logoB: "/assets/image/italie.png",
    termine: false,
    resultat: "",
    score: ""
  },
  {
    date: "2025-08-11",
    heure: "12:30",
    equipeA: "ASSM",
    equipeB: "CSA",
    lieu: "Arena sport Toamasina",
    competition: "U-18",
    categorie: "Femme",
    logoA: "/assets/image/etats-unis.png",
    logoB: "/assets/image/france.png",
    termine: true,
    resultat: "1 - 3",
    score: "20-25 | 25-18 | 18-25 | 23-25"
  },
  {
    date: "2025-08-08",
    heure: "12:30",
    equipeA: "ASSM",
    equipeB: "CSA",
    lieu: "Arena sport Toamasina",
    competition: "U-18",
    categorie: "Femme",
    logoA: "/assets/image/etats-unis.png",
    logoB: "/assets/image/france.png",
    termine: false,
    resultat: "",
    score: ""
  },
  {
    date: "2025-08-08",
    heure: "11:30",
    equipeA: "ASI",
    equipeB: "CVBA",
    lieu: "Arena sport Toamasina",
    competition: "U-18",
    categorie: "Homme",
    logoA: "/assets/image/allemagne.png",
    logoB: "/assets/image/italie.png",
    termine: true,
    resultat: "3 - 2",
    score: "25-20 | 21-25 | 18-25 | 25-21 | 15-13"
  },
];